/*
 * EMService
 * Easemob Rest API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.easemob.im.api.model;

import java.util.Objects;
import com.easemob.im.api.model.EMReactionResource;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.easemob.im.JSON;

/**
 * EMGetReactionListResource
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-19T14:46:11.706022+08:00[Asia/Shanghai]")
public class EMGetReactionListResource {
  public static final String SERIALIZED_NAME_MSG_ID = "msgId";
  @SerializedName(SERIALIZED_NAME_MSG_ID)
  private String msgId;

  public static final String SERIALIZED_NAME_REACTION_LIST = "reactionList";
  @SerializedName(SERIALIZED_NAME_REACTION_LIST)
  private List<EMReactionResource> reactionList;

  public EMGetReactionListResource() {
  }

  public EMGetReactionListResource msgId(String msgId) {
    
    this.msgId = msgId;
    return this;
  }

   /**
   * Reaction 对应的消息 ID
   * @return msgId
  **/
  @javax.annotation.Nullable
  public String getMsgId() {
    return msgId;
  }


  public void setMsgId(String msgId) {
    this.msgId = msgId;
  }


  public EMGetReactionListResource reactionList(List<EMReactionResource> reactionList) {
    
    this.reactionList = reactionList;
    return this;
  }

  public EMGetReactionListResource addReactionListItem(EMReactionResource reactionListItem) {
    if (this.reactionList == null) {
      this.reactionList = new ArrayList<>();
    }
    this.reactionList.add(reactionListItem);
    return this;
  }

   /**
   * 单个消息的 Reaction 列表
   * @return reactionList
  **/
  @javax.annotation.Nullable
  public List<EMReactionResource> getReactionList() {
    return reactionList;
  }


  public void setReactionList(List<EMReactionResource> reactionList) {
    this.reactionList = reactionList;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EMGetReactionListResource getReactionListResource = (EMGetReactionListResource) o;
    return Objects.equals(this.msgId, getReactionListResource.msgId) &&
        Objects.equals(this.reactionList, getReactionListResource.reactionList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(msgId, reactionList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EMGetReactionListResource {\n");
    sb.append("    msgId: ").append(toIndentedString(msgId)).append("\n");
    sb.append("    reactionList: ").append(toIndentedString(reactionList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("msgId");
    openapiFields.add("reactionList");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to EMGetReactionListResource
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EMGetReactionListResource.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EMGetReactionListResource is not found in the empty JSON string", EMGetReactionListResource.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!EMGetReactionListResource.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `EMGetReactionListResource` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("msgId") != null && !jsonObj.get("msgId").isJsonNull()) && !jsonObj.get("msgId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `msgId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("msgId").toString()));
      }
      if (jsonObj.get("reactionList") != null && !jsonObj.get("reactionList").isJsonNull()) {
        JsonArray jsonArrayreactionList = jsonObj.getAsJsonArray("reactionList");
        if (jsonArrayreactionList != null) {
          // ensure the json data is an array
          if (!jsonObj.get("reactionList").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `reactionList` to be an array in the JSON string but got `%s`", jsonObj.get("reactionList").toString()));
          }

          // validate the optional field `reactionList` (array)
          for (int i = 0; i < jsonArrayreactionList.size(); i++) {
            EMReactionResource.validateJsonElement(jsonArrayreactionList.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EMGetReactionListResource.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EMGetReactionListResource' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EMGetReactionListResource> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EMGetReactionListResource.class));

       return (TypeAdapter<T>) new TypeAdapter<EMGetReactionListResource>() {
           @Override
           public void write(JsonWriter out, EMGetReactionListResource value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EMGetReactionListResource read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of EMGetReactionListResource given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of EMGetReactionListResource
  * @throws IOException if the JSON string is invalid with respect to EMGetReactionListResource
  */
  public static EMGetReactionListResource fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EMGetReactionListResource.class);
  }

 /**
  * Convert an instance of EMGetReactionListResource to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

