/*
 * EMService
 * Easemob Rest API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.easemob.im.api;

import com.easemob.im.ApiException;
import org.junit.jupiter.api.Test;

import static org.junit.Assert.assertThrows;

/**
 * API tests for HistoryMessageApi
 */
public class HistoryMessageApiTest extends AbstractTest {

    private final HistoryMessageApi api = new HistoryMessageApi();

    public HistoryMessageApiTest() {
    }

    /**
     * 获取历史消息记录
     *
     * 你可以从服务端获取用户发送的历史消息的记录。单次请求获取从指定起始时间开始一小时内的发送的历史消息记录。查询历史消息记录时存在一定延时，无法实时获取。过期的历史消息记录无法获取。文档介绍：https://docs-im-beta.easemob.com/document/server-side/message_historical.html
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void historyMessageTest() throws ApiException {
        String time = "2024012415";
        assertThrows(ApiException.class, () -> api.historyMessage(time));
    }

}
